import {expect,test} from '@playwright/test';
const path='/tests/browser/p18-household.html';
test('member preparation is usable but never sends data or claims sharing',async({page})=>{
 const requests:string[]=[];
 page.on('request',request=>{if(request.method()!=='GET')requests.push(request.url());});
 await page.goto(path);
 await page.getByRole('button',{name:'Family sharing'}).click();
 const dlg=page.getByRole('dialog',{name:'Family sharing'});
 await expect(dlg).toBeVisible();
 await expect(dlg.getByText(/Sharing is unavailable until/)).toBeVisible();
 await expect(dlg.getByRole('button',{name:/Revoke member/})).toBeDisabled();
 await dlg.getByLabel('Email address').fill('Member@Example.com');
 await dlg.getByLabel('Proposed access').selectOption('editor');
 await dlg.getByRole('button',{name:'Review invitation draft'}).click();
 await expect(dlg.getByText('Draft prepared — not sent')).toBeVisible();
 await expect(dlg.getByText('member@example.com')).toBeVisible();
 await expect(dlg.getByRole('button',{name:/Send invitation/})).toBeDisabled();
 expect(requests).toEqual([]);
 await page.keyboard.press('Escape');
 await expect(dlg).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Family sharing'})).toBeFocused();
 await page.getByRole('button',{name:'Family sharing'}).click();
 await expect(page.getByRole('dialog',{name:'Family sharing'}).getByText('Draft prepared — not sent')).toHaveCount(0);
});
test('rejects malformed invitations and preserves keyboard boundaries at narrow widths',async({page})=>{
 await page.goto(path);
 await page.getByRole('button',{name:'Family sharing'}).click();
 const dlg=page.getByRole('dialog',{name:'Family sharing'});
 await dlg.getByRole('button',{name:'Review invitation draft'}).click();
 await expect(dlg.getByRole('alert')).toContainText('valid email');
 await dlg.getByLabel('Email address').fill('two@example.com,other@example.com');
 await dlg.getByRole('button',{name:'Review invitation draft'}).click();
 await expect(dlg.getByRole('alert')).toBeVisible();
 await expect(dlg.getByText('Draft prepared — not sent')).toHaveCount(0);
 await dlg.getByLabel('Email address').fill('good@example.com');
 await dlg.getByRole('button',{name:'Review invitation draft'}).click();
 await expect(dlg.getByRole('status')).toContainText('Draft prepared');
 await page.keyboard.press('Shift+Tab');
 expect(await dlg.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 const dims=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);
 expect(dims[0]).toBeLessThanOrEqual(dims[1]+1);
});
test('reduced motion and 200% zoom preserve visible denial without horizontal overflow',async({page},testInfo)=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto(path);
 await page.getByRole('button',{name:'Family sharing'}).click();
 await page.evaluate(()=>{document.documentElement.style.zoom='2';});
 const dlg=page.getByRole('dialog',{name:'Family sharing'});
 await expect(dlg.getByText(/Nothing prepared here is sent/)).toBeVisible();
 const dims=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);
 expect(dims[0]).toBeLessThanOrEqual(dims[1]+1);
 await page.screenshot({path:'test-results/p18-'+testInfo.project.name+'-zoom200.png',fullPage:true});
});
