import {expect,test} from '@playwright/test';
const url='/tests/browser/p19-intelligence.html';
test('disabled by default, opt-in local recommendations and no outbound writes',async({page},testInfo)=>{
 const nonGet:string[]=[];
 page.on('request',r=>{if(r.method()!=='GET')nonGet.push(r.url());});
 await page.goto(url);
 await expect(page.getByText('Off by default. Enable for local, explainable suggestions.')).toBeVisible();
 await expect(page.getByRole('button',{name:'Review Tomato pasta'})).toHaveCount(0);
 await page.getByRole('checkbox',{name:'Enable suggestions'}).check();
 await expect(page.getByRole('button',{name:'Review Tomato pasta'})).toBeVisible();
 await expect(page.getByText(/1 of 2 required ingredient types/)).toBeVisible();
 await expect(page.getByText(/not an allergy or food-safety filter/i)).toBeVisible();
 await expect(page.getByText('Other owner secret')).toHaveCount(0);
 await page.getByRole('button',{name:'Review Tomato pasta'}).click();
 await expect(page.getByTestId('opened-recipe')).toHaveText('Opened: Tomato pasta');
 await page.getByRole('button',{name:'Open meal planner'}).click();
 await expect(page.getByTestId('plan-notice')).toContainText('no meals assigned');
 expect(nonGet).toEqual([]);
 await page.screenshot({path:'test-results/p19-'+testInfo.project.name+'-enabled.png',fullPage:true});
});
test('explicit time filter, manual name hiding, persistence and cross-account isolation',async({page})=>{
 await page.goto(url);
 await page.getByRole('checkbox',{name:/Enable suggestions|Suggestions on/}).check();
 await page.getByRole('combobox',{name:'Maximum cooking time'}).selectOption('15');
 await expect(page.getByRole('button',{name:'Review Tomato pasta'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Review Rice bowl'})).toBeVisible();
 await page.getByRole('textbox',{name:'Hide named ingredients'}).fill('rice');
 await page.getByRole('button',{name:'Hide',exact:true}).click();
 await expect(page.getByRole('button',{name:'Review Rice bowl'})).toHaveCount(0);
 await expect(page.getByRole('status')).toContainText('No saved recipes meet these filters');
 await page.reload();
 await expect(page.getByRole('checkbox',{name:'Suggestions on'})).toBeChecked();
 await expect(page.getByRole('combobox',{name:'Maximum cooking time'})).toHaveValue('15');
 await page.getByRole('button',{name:'Account B'}).click();
 await expect(page.getByTestId('current-account')).toHaveText('B');
 await expect(page.getByRole('checkbox',{name:'Enable suggestions'})).not.toBeChecked();
 await expect(page.getByText('Other owner secret')).toHaveCount(0);
 await page.getByRole('button',{name:'Account A'}).click();
 await expect(page.getByRole('checkbox',{name:'Suggestions on'})).toBeChecked();
});
test('reduced-motion + 200% CSS zoom with keyboard controls reflows',async({page},testInfo)=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.goto(url);
 await page.getByRole('checkbox',{name:'Enable suggestions'}).check();
 await page.keyboard.press('Tab');
 await page.evaluate(()=>{document.documentElement.style.zoom='2';});
 await expect(page.getByRole('button',{name:'Review Tomato pasta'})).toBeVisible();
 const dims=await page.evaluate(()=>[document.documentElement.scrollWidth,document.documentElement.clientWidth]);
 expect(dims[0]!).toBeLessThanOrEqual(dims[1]!+1);
 const duration=await page.locator('.cooking-idea').evaluate(el=>getComputedStyle(el).transitionDuration);
 expect(duration.split(',').map(x=>x.trim())).toEqual(['0s']);
 await page.screenshot({path:'test-results/p19-'+testInfo.project.name+'-zoom200.png',fullPage:true});
});
